#define TRANSMITTANCE_TEXTURE_WIDTH 256
#define TRANSMITTANCE_TEXTURE_HEIGHT 64

#define SCATTERING_TEXTURE_R_SIZE 32
#define SCATTERING_TEXTURE_MU_SIZE 128
#define SCATTERING_TEXTURE_MU_S_SIZE 32
#define SCATTERING_TEXTURE_NU_SIZE 8

#define SCATTERING_TEXTURE_WIDTH (SCATTERING_TEXTURE_NU_SIZE * SCATTERING_TEXTURE_MU_S_SIZE)
#define SCATTERING_TEXTURE_HEIGHT SCATTERING_TEXTURE_MU_SIZE
#define SCATTERING_TEXTURE_DEPTH SCATTERING_TEXTURE_R_SIZE

#define IRRADIANCE_TEXTURE_WIDTH 64
#define IRRADIANCE_TEXTURE_HEIGHT 16

#define ATM_TRANSMITTANCE_SLOT 7
#define ATM_SINGLE_RAYLEIGH_SCATTERING_SLOT 6
#define ATM_SINGLE_MIE_SCATTERING_SLOT 5
#define ATM_MULTIPLE_SCATTERING_SLOT 4
#define ATM_SCATTERING_DENSITY 3
#define ATM_IRRADIANCE_SLOT 2
#define ATM_SCATTERING_SLOT 1
