#define BS_MORPH_AFFECTED_STAGE 1
#define BS_ALL_MORPH_VERTEX_ID_STAGE 2
#define BS_ACTIVE_MORPH_DATA_STAGE 3
#define BS_FINAL_MORPH_AFFECTED_STAGE 4
#define BS_CHANGED_MORPH_INDEX_STAGE 5
#define BS_ALPHA_STAGE 6