#define CLASSIFICATICON_GRID_SIZE 1
#define DISTANCE_GRID_SIZE 16
#define IRRADIANCE_GRID_SIZE 8
#define RELOCATION_GRID_SIZE 1

#define CLA_MAP_SLOT 8
#define DIS_MAP_SLOT 9
#define IRR_MAP_SLOT 10
#define REL_MAP_SLOT 11
