#define DISTANCE_GRID_SIZE 16
#define IRRADIANCE_GRID_SIZE 8
#define RELOCATION_GRID_SIZE 1
#define CLASSIFICATICON_GRID_SIZE 1

#define DIS_MAP_SLOT 4
#define IRR_MAP_SLOT 5
#define REL_MAP_SLOT 6
#define CLA_MAP_SLOT 7
