#define POINT_LIGHT_LENGTH 32
#define SPOT_LIGHT_LENGTH 64
#define DIRECTIONAL_LIGHT_LENGTH 32
#define SPHERE_LIGHT_LENGTH 48
#define DISK_LIGHT_LENGTH 48
#define RECTANGLE_LIGHT_LENGTH 64
#define TUBE_LIGHT_LENGTH 64
