name: win64_vs2022_clang

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-engine:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3.2.0
      with:
        submodules: recursive

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Make 3rdParty
      run: ${{github.workspace}}/MakeThirdParty_vs2022-clang.bat
      
    - name: Make Engine
      run: ${{github.workspace}}/MakeEngine_vs2022-clang.bat

    - name: Build Debugx64
      run: msbuild ${{github.workspace}}/CatDogEngine.sln /p:Configuration=Debug /p:Platform=x64
      
    - name: Build Releasex64
      run: msbuild ${{github.workspace}}/CatDogEngine.sln /p:Configuration=Release /p:Platform=x64
